INPUT_VARIABLE_LOCATION = 1
OUTPUT_VARIABLE_LOCATION = 2
EXPECTED_NUMBER_OF_ARGUMENTS = 3

SECONDS_IN_HOUR = 3600
SECONDS_IN_MINUTES = 60
MILLISECONDS_IN_SECONDS = 1000
SECTIONS_IN_TIMESTAMP = 4
ZIPCODE_LENGTH = 5